services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://trimuser:urlproj@postgres:5432/trimtrack
      - REDIS_URL=redis://redis:6379
      - PORT=3000
      - BASE_URL=http://localhost:3000
      - JWT_SECRET=trimtrackv1
    depends_on:
      - postgres
      - redis
    
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=trimuser
      - POSTGRES_PASSWORD=urlproj
      - POSTGRES_DB=trimtrack
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/src/db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
  
volumes:
  pgdata: